# Generated by Django 5.1.1 on 2024-10-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_billet', models.CharField(max_length=30)),
                ('Type_billet', models.CharField(max_length=30)),
                ('Id_utilisateur', models.CharField(max_length=30)),
                ('Id_evenement', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_evenement', models.IntegerField(max_length=30)),
                ('Id_utilisateur', models.IntegerField(max_length=30)),
                ('Type_evenement', models.CharField(max_length=30)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Description_evenement', models.CharField(max_length=200)),
                ('Nom_user', models.CharField(max_length=30)),
                ('Emal_user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paiement', models.CharField(max_length=50)),
                ('Nom_utilisateur', models.CharField(max_length=30)),
                ('id_evenement', models.CharField(max_length=30)),
                ('Date_paiement', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilisateur', models.CharField(max_length=30)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
